export const ISSUES = {
  SET_USERNAME: 'ISSUES/SET_USERNAME',
  SET_REPO: 'ISSUES/SET_REPO',
  FETCH_ISSUES: 'ISSUES/FETCH_ISSUES',
  SET_ISSUES: 'ISSUES/SET_ISSUES',
  LOADING_START: 'ISSUES/LOADING_START',
  LOADING_END: 'ISSUES/LOADING_END',
  SET_COUNT: 'ISSUES/SET_COUNT',
  SET_PAGE: 'ISSUES/SET_PAGE',
}

export const NOTICE = {
  SHOW_ERROR: 'ISSUES/SHOW_ERROR',
  CLEAR_ERROR: 'ISSUES/CLEAR_ERROR',
}

// export const SET_USERNAME = 'ISSUES/SET_USERNAME'
// export const SET_REPO = 'ISSUES/SET_REPO'
// export const FETCH_ISSUES = 'ISSUES/FETCH_ISSUES'
// export const SET_ISSUES = 'ISSUES/SET_ISSUES'
// export const LOADING_START = 'ISSUES/LOADING_START'
// export const LOADING_END = 'ISSUES/LOADING_END'
// export const SHOW_ERROR = 'ISSUES/SHOW_ERROR'
// export const CLEAR_ERROR = 'ISSUES/CLEAR_ERROR'
// export const SET_COUNT = 'ISSUES/SET_COUNT'
// export const SET_PAGE = 'ISSUES/SET_PAGE'

// export const SET_ERROR = 'ISSUES/SET_ERROR'
// export const REMOVE_ERROR = 'ISSUES/REMOVE_ERROR'
